/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 study_room.glb 
Author: BazzaTRD (https://sketchfab.com/BazzaTRD)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/study-room-d8d093f97dfb45efb2c632b53a12718f
Title: Study Room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function StudyRoom(props) {
  const { nodes, materials } = useGLTF('/models/study_room.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.696}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={2}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.room} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.room2} />
          </group>
          <group position={[1.291, 0.564, -0.855]} rotation={[Math.PI / 2, 0, 0]} scale={[0.262, 1.102, 0.525]}>
            <mesh geometry={nodes.Object_11.geometry} material={materials.cupboard} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.metalic} />
          </group>
          <group position={[-1.706, 1.602, -1.181]} scale={[0.193, 0.406, 0.451]}>
            <mesh geometry={nodes.Object_42.geometry} material={materials['case']} />
            <mesh geometry={nodes.Object_43.geometry} material={materials.mesh_back} />
          </group>
          <group position={[-1.669, 1.602, -0.73]} rotation={[Math.PI / 2, 0, 0]} scale={[0.156, 0.156, 0.402]}>
            <mesh geometry={nodes.Object_45.geometry} material={materials.wire_mesh} />
            <mesh geometry={nodes.Object_46.geometry} material={materials.wire_mesh} />
          </group>
          <group position={[-1.811, 3.12, -1.7]} scale={[0.03, 0.175, 0.175]}>
            <mesh geometry={nodes.Object_62.geometry} material={materials.book1} />
            <mesh geometry={nodes.Object_63.geometry} material={materials.book2} />
            <mesh geometry={nodes.Object_64.geometry} material={materials.book3} />
          </group>
          <group position={[-1.09, 3.11, -1.7]} scale={[0.03, 0.175, 0.175]}>
            <mesh geometry={nodes.Object_66.geometry} material={materials.book2} />
            <mesh geometry={nodes.Object_67.geometry} material={materials.book3} />
          </group>
          <group position={[-1.811, 3.503, -1.7]} scale={[0.03, 0.166, 0.175]}>
            <mesh geometry={nodes.Object_69.geometry} material={materials.book1} />
            <mesh geometry={nodes.Object_70.geometry} material={materials.book2} />
            <mesh geometry={nodes.Object_71.geometry} material={materials.book3} />
          </group>
          <group position={[-1.811, 2.752, -1.7]} scale={[0.03, 0.175, 0.175]}>
            <mesh geometry={nodes.Object_73.geometry} material={materials.book3} />
            <mesh geometry={nodes.Object_74.geometry} material={materials.book1} />
            <mesh geometry={nodes.Object_75.geometry} material={materials.book2} />
          </group>
          <group position={[-1.075, 2.739, -1.7]} scale={[0.03, 0.175, 0.175]}>
            <mesh geometry={nodes.Object_79.geometry} material={materials.book2} />
            <mesh geometry={nodes.Object_80.geometry} material={materials.book1} />
          </group>
          <group position={[-0.606, 3.12, -1.7]} scale={[0.03, 0.175, 0.175]}>
            <mesh geometry={nodes.Object_82.geometry} material={materials.book2} />
            <mesh geometry={nodes.Object_83.geometry} material={materials.book1} />
            <mesh geometry={nodes.Object_84.geometry} material={materials.book3} />
          </group>
          <group position={[0.12, 3.1, -1.7]} scale={[0.03, 0.175, 0.175]}>
            <mesh geometry={nodes.Object_86.geometry} material={materials.book1} />
            <mesh geometry={nodes.Object_87.geometry} material={materials.book3} />
            <mesh geometry={nodes.Object_88.geometry} material={materials.book2} />
          </group>
          <group position={[-1.143, 1.227, -0.692]} rotation={[0, -0.491, -Math.PI / 2]} scale={[0.03, 0.166, 0.175]}>
            <mesh geometry={nodes.Object_96.geometry} material={materials.book3} />
            <mesh geometry={nodes.Object_97.geometry} material={materials.pages} />
          </group>
          <group position={[0.072, 1.627, -1.792]} scale={[0.506, 0.288, 0.007]}>
            <mesh geometry={nodes.Object_105.geometry} material={materials['monitor.001']} />
            <mesh geometry={nodes.Object_106.geometry} material={materials['league.001']} />
          </group>
          <group position={[-1.024, 1.627, -1.355]} rotation={[0, 0.802, 0]} scale={[0.506, 0.288, 0.007]}>
            <mesh geometry={nodes.Object_108.geometry} material={materials['monitor.001']} />
            <mesh geometry={nodes.Object_109.geometry} material={materials['Material.002']} />
          </group>
          <mesh geometry={nodes.Object_7.geometry} material={materials.table} position={[-1, 1.2, -1.303]} scale={[1, 1, 0.7]} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.table} position={[1.291, 0.58, -1.445]} rotation={[0, -Math.PI / 2, 0]} scale={[0.561, 0.533, 0.276]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.table} position={[-1.546, 0.58, 0.375]} scale={[0.46, 0.533, 0.57]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.cupboard} position={[-1.063, 0.562, 0.375]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.547, 0.902, 0.525]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.metalic} position={[-1.063, 1.025, 0.393]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.022, 0.033, 0.018]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.metalic} position={[1.539, 0.67, -0.716]} scale={[0.01, 0.02, 0.221]} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.tray} position={[-1.526, 1.207, 0.43]} rotation={[0, 0.111, 0]} scale={[0.315, 0.231, 0.608]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials['case']} position={[-0.2, 1.221, -1.101]} rotation={[-Math.PI, -0.137, -Math.PI]} scale={[-0.41, 0.021, 0.161]} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.cupboard} position={[-0.581, 1.241, -1.136]} rotation={[-3.088, -0.137, -3.134]} scale={[-0.353, 0.01, 0.129]} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.monitor} position={[0.072, 1.217, -1.731]} scale={[0.437, 0.017, 0.152]} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.monitor} position={[-0.98, 1.217, -1.313]} rotation={[0, 0.802, 0]} scale={[0.437, 0.017, 0.152]} />
          <mesh geometry={nodes.Object_32.geometry} material={materials['Material.004']} position={[0.476, 0.006, 0.57]} scale={[1.374, 0.01, 1.193]} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.folder} position={[-1.523, 1.207, 0.731]} scale={0.23} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.paper} position={[-1.643, 1.207, 0.128]} rotation={[0, 0.029, 0]} scale={[0.175, 0.281, 0.28]} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.paper} position={[1.212, 1.207, -1.206]} rotation={[0, 0.444, 0]} scale={[0.175, 0.281, 0.28]} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.folder} position={[1.321, 0.556, -0.756]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.171} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.mesh_back} position={[-1.669, 1.602, -0.731]} rotation={[Math.PI / 2, 0, 0]} scale={[0.156, 0.156, 0.405]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.material_0} position={[-1.843, 1.913, -0.751]} rotation={[0, 0, -Math.PI / 2]} scale={[0.014, 0.008, 0.008]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.material_0} position={[-1.843, 1.769, -0.756]} rotation={[Math.PI / 2, 0, 0]} scale={[0.004, 0.017, 0.004]} />
          <mesh geometry={nodes.Object_54.geometry} material={materials.table} position={[-0.144, 3.12, -1.7]} rotation={[0, Math.PI / 2, 0]} scale={[-0.339, 0.604, 1.885]} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.mesh_back} position={[0.562, 1.202, -1.141]} rotation={[0, -0.145, 0]} scale={0.258} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.mesh_back} position={[0.562, 1.202, -1.141]} rotation={[0, -0.145, 0]} scale={0.258} />
          <mesh geometry={nodes.Object_60.geometry} material={materials.Material} position={[0.492, 1.202, -1.148]} rotation={[0, 0.501, 0]} scale={[0.049, 0.049, 0.072]} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.book3} position={[-0.038, 2.606, -1.7]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.166, 0.175]} />
          <mesh geometry={nodes.Object_90.geometry} material={materials.book2} position={[-0.038, 2.664, -1.725]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.166, 0.175]} />
          <mesh geometry={nodes.Object_92.geometry} material={materials.book3} position={[1.154, 2.965, -1.7]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.166, 0.175]} />
          <mesh geometry={nodes.Object_94.geometry} material={materials.book1} position={[1.154, 3.023, -1.725]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.166, 0.175]} />
          <mesh geometry={nodes.Object_99.geometry} material={materials.chair_stand} position={[-0.083, 0.322, -0.341]} scale={[0.045, 0.149, 0.045]} />
          <mesh geometry={nodes.Object_101.geometry} material={materials.metalic} position={[-0.083, 0.198, -0.341]} scale={[0.062, 0.019, 0.062]} />
          <mesh geometry={nodes.Object_103.geometry} material={materials.chair} position={[0.025, 0.706, -0.507]} rotation={[0, -0.549, 0]} scale={[0.323, 0.342, 0.342]} />
          <mesh geometry={nodes.Object_111.geometry} material={materials['Material.006']} position={[-0.237, 1.214, -2.182]} rotation={[0.015, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_113.geometry} material={materials['Material.006']} position={[0.484, 1.214, -2.161]} rotation={[0.015, Math.PI / 2, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/study_room.glb')
